apiVersion: v1
kind: Pod
metadata:
  name: frac-hi
  annotations: { nvidia.com/use-gpuuuid: "GPU-c837f0dc-1909-27bf-fb57-1257b191226d" }
spec:
  schedulerName: hami-scheduler
  restartPolicy: Never
  containers:
  - name: t
    image: docker.io/pytorch/pytorch:2.10.0-cuda13.0-cudnn9-runtime
    command: ["sh","-c","uname -r; python /probe/gpuprobe.py"]
    env: [{ name: MODE, value: matmul }, { name: SECONDS_, value: "40" }]
    resources:
      limits: { nvidia.com/gpu: 1, nvidia.com/gpumem: 100000, nvidia.com/gpucores: 75, cpu: "8", memory: 32Gi }
    volumeMounts: [{ name: probe, mountPath: /probe }]
  volumes: [{ name: probe, configMap: { name: gpuprobe } }]
---
apiVersion: v1
kind: Pod
metadata:
  name: frac-lo
  annotations: { nvidia.com/use-gpuuuid: "GPU-c837f0dc-1909-27bf-fb57-1257b191226d" }
spec:
  schedulerName: hami-scheduler
  restartPolicy: Never
  containers:
  - name: t
    image: docker.io/pytorch/pytorch:2.10.0-cuda13.0-cudnn9-runtime
    command: ["sh","-c","uname -r; python /probe/gpuprobe.py"]
    env: [{ name: MODE, value: matmul }, { name: SECONDS_, value: "40" }]
    resources:
      limits: { nvidia.com/gpu: 1, nvidia.com/gpumem: 100000, nvidia.com/gpucores: 25, cpu: "8", memory: 32Gi }
    volumeMounts: [{ name: probe, mountPath: /probe }]
  volumes: [{ name: probe, configMap: { name: gpuprobe } }]
---
