apiVersion: midori.phoenix/v1alpha1
kind: Tenant
metadata: { name: tenant-nv-b }
spec:
  management: Manage
  quota: { gpus: 2, gpuMemoryMiB: 92136 }
  controlPlane: { apiNodePort: 32043, size: small }
